# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-15 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publishers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='name')),
                ('type', models.IntegerField(choices=[(0, 'Point'), (1, 'LineString'), (2, 'Polygon'), (3, 'Feature')], default=2)),
                ('coordinates', django_mysql.models.JSONField(default=dict, verbose_name='coordinates of the data type defined')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this publisher should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publishers.Publisher', verbose_name='Reference to the publisher table')),
            ],
            options={
                'verbose_name': 'Service Area',
                'verbose_name_plural': 'Service Areas',
            },
        ),
    ]
