# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-16 04:35
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('servicearea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearea',
            name='coordinates',
            field=jsonfield.fields.JSONField(default=dict, verbose_name='coordinates of the data type defined'),
        ),
    ]
